Repository u-root/u-root, pull requests merged in 2021-08, with the labels that each got.

#2080 Require stringer be implemented for menu entries
  pkg/boot/menu/menu.go
  pkg/boot/menu/menu_test.go
Labels: Waiting for Author, automerge

#2085 Add support for specifying build tags
  u-root.go
Labels: automerge

#2091 cmds/core/backoff: simple backoff command
  cmds/core/backoff/main.go
  cmds/core/backoff/main_test.go
Labels: automerge, Waiting for Reviewer

#2095 Update minimum Go version
  README.md
Labels: automerge

#2097 Add a single test to each empty file
  pkg/bb/bbmain/pkg_test.go
  pkg/boot/bootcmd/pkg_test.go
  pkg/boot/boottest/pkg_test.go
  pkg/boot/localboot/pkg_test.go
  pkg/boot/netboot/pkg_test.go
  pkg/boot/netboot/simple/pkg_test.go
  pkg/boot/util/pkg_test.go
  pkg/checker/pkg_test.go
  pkg/cmos/pkg_test.go
  pkg/cp/cmp/pkg_test.go
  pkg/fb/pkg_test.go
  pkg/golang/pkg_test.go
  pkg/ipmi/blobs/pkg_test.go
  pkg/ipmi/ocp/pkg_test.go
  pkg/ipmi/pkg_test.go
  pkg/kexecbin/pkg_test.go
  pkg/libinit/pkg_test.go
  pkg/ls/pkg_test.go
  pkg/mei/pkg_test.go
  pkg/qemu/pkg_test.go
  pkg/recovery/pkg_test.go
  pkg/rng/pkg_test.go
  pkg/rtc/pkg_test.go
  pkg/securelaunch/eventlog/pkg_test.go
  pkg/securelaunch/launcher/pkg_test.go
  pkg/securelaunch/measurement/pkg_test.go
  pkg/securelaunch/pkg_test.go
  pkg/securelaunch/policy/pkg_test.go
  pkg/securelaunch/tpm/pkg_test.go
  pkg/sh/pkg_test.go
  pkg/strace/internal/binary/pkg_test.go
  pkg/testutil/pkg_test.go
  pkg/tss/pkg_test.go
  pkg/txtlog/pkg_test.go
  pkg/ubinary/pkg_test.go
  pkg/uefivars/vartest/pkg_test.go
  pkg/uio/uiotest/pkg_test.go
  pkg/ulog/ulogtest/pkg_test.go
  pkg/uroot/initramfs/test/pkg_test.go
  pkg/uroot/test/bar/pkg_test.go
  pkg/uroot/util/pkg_test.go
  pkg/vmtest/internal/json2test/pkg_test.go
  pkg/vmtest/pkg_test.go
  pkg/watchdog/pkg_test.go
  pkg/watchdogd/pkg_test.go
Labels: automerge, Waiting for Author

#2092 [ntpdate] Take servers from cmdline, allow setting RTC
  cmds/core/hwclock/hwclock.go
  cmds/core/ntpdate/ntpdate.go
  cmds/core/ntpdate/ntpdate_test.go
  pkg/ntpdate/ntpdate.go
  pkg/ntpdate/ntpdate_test.go
  pkg/ntpdate/testdata/ntp.conf
  pkg/rtc/rtc.go
  pkg/rtc/rtc_linux.go
Labels: Waiting for Author

#2100 Fix the warning on modules
  README.md
Labels: automerge

#2090 Move etc configurations to tmpfs
  pkg/libinit/root_linux.go
Labels: Awaiting author

#2106 tools/makebb: add -c switch so it lists commands
  tools/makebb/makebb.go
Labels: Awaiting author
