Repository u-root/u-root, pull requests merged in 2021-12, with the labels that each got.

#2197 Guidelines for writing unit tests
  CONTRIBUTING.md
Labels: automerge

#2206 u-root: default to building with gobusybox if GO111MODULE!="off"
  u-root.go
Labels: automerge

#2205 bzimage: re enable testing
  cmds/exp/bzimage/bzimage_test.go
Labels: automerge

#2189 Add coverage reporting from VM tests
  .circleci/config.yml
  integration/testcmd/gotest/uinit/gotest.go
  pkg/vmtest/gotest.go
Labels: Awaiting reviewer, coverage

#2215 Cover/pkg/cp 2try
  cmds/core/cp/cp_test.go
  pkg/cp/cmp/cmp.go
  pkg/cp/cmp/pkg_test.go
  pkg/cp/cp_test.go
Labels: Awaiting reviewer, coverage

#2230 Cover/cmds/core/date
  cmds/core/date/date.go
  cmds/core/date/date_test.go
Labels: Awaiting author, coverage

#2246 Remove ash and pkg/complete
  cmds/exp/ash/ash.go
  cmds/exp/ash/cd.go
  cmds/exp/ash/exit.go
  cmds/exp/ash/parse.go
  cmds/exp/ash/rush.go
  cmds/exp/ash/rush_test.go
  cmds/exp/ash/time.go
  cmds/exp/ash/tty_linux.go
  pkg/complete/complete_test.go
  pkg/complete/doc.go
  pkg/complete/env.go
  pkg/complete/file.go
  pkg/complete/io.go
  pkg/complete/line.go
  pkg/complete/line_test.go
  pkg/complete/multi.go
  pkg/complete/newline.go
  pkg/complete/prefix.go
  pkg/complete/prefix_test.go
  pkg/complete/string.go
  pkg/complete/types.go
  pkg/complete/vars.go
Labels: automerge, Awaiting reviewer, coverage
