Repository u-root/u-root, pull requests merged in 2021-07, with the labels that each got.

#2054 Update roadmap
  roadmap.md
Labels: Waiting for Author

#2057 cmds/exp/uefiboot: Add manual
  cmds/exp/uefiboot/main.go
Labels: automerge

#2061 change uefipayload to linuxboot fork
  .circleci/images/test-image-amd64/Dockerfile
  cmds/exp/uefiboot/README.md
Labels: automerge

#2060 Create spi package for Linux spidev driver
  cmds/contrib/spidev/spidev.go
  cmds/contrib/spidev/spidev_test.go
  pkg/spi/spidev_linux.go
  pkg/spi/spidev_linux_test.go
Labels: Waiting for Reviewer

#2065 Add flash and sfdp packages
  cmds/contrib/spidev/spidev.go
  cmds/contrib/spidev/spidev_test.go
  pkg/flash/flash.go
  pkg/flash/flash_test.go
  pkg/flash/op/op.go
  pkg/flash/sfdp/sfdp.go
  pkg/flash/sfdp/sfdp_test.go
  pkg/flash/spimock/spimock.go
  pkg/spi/spidev_linux.go
  pkg/spi/spidev_linux_test.go
Labels: automerge

#2069 systemboot: add OCP Crater Lake to supported OEM product list
  cmds/boot/systemboot/main.go
Labels: Waiting for Author, automerge

#2068 Add boot rank to OSImage interface.
  pkg/boot/bls/bls.go
  pkg/boot/bls/bls_test.go
  pkg/boot/bls/testdata/fedora_32.json
  pkg/boot/bls/testdata/madeup.json
  pkg/boot/boot.go
  pkg/boot/boottest/json.go
  pkg/boot/fit/fit.go
  pkg/boot/fit/fit_test.go
  pkg/boot/grub/testdata_new/CentOS_7_x86_64_DVD_1810.json
  pkg/boot/grub/testdata_new/CentOS_7_x86_64_DVD_1810_efi_install_sda1.json
  pkg/boot/grub/testdata_new/CentOS_7_x86_64_DVD_1810_legacy_install_sda1.json
  pkg/boot/grub/testdata_new/debian_10_4_installed.json
  pkg/boot/grub/testdata_new/debian_9_install.json
  pkg/boot/grub/testdata_new/fedora_27_install.json
  pkg/boot/grub/testdata_new/qubes_3_2_boot.json
  pkg/boot/grub/testdata_new/rhel_7_8_another.json
  pkg/boot/grub/testdata_new/rhel_7_8_installed.json
  pkg/boot/grub/testdata_new/ubuntu_16_04_boot.json
  pkg/boot/linux.go
  pkg/boot/linux_test.go
  pkg/boot/localboot/localboot.go
  pkg/boot/multiboot.go
  pkg/boot/multiboot_test.go
  pkg/boot/syslinux/testdata/debian_10_install.json
  pkg/boot/syslinux/testdata/debian_9_install.json
  pkg/boot/syslinux/testdata/fedora_27_install.json
  pkg/boot/syslinux/testdata/qubes_3_2_install.json
Labels: automerge

#2078 cmd/time: add a time command
  cmds/core/time/time.go
  cmds/core/time/time_test.go
Labels: Waiting for Reviewer

#2052 curl: enable fetch without cache
  pkg/curl/mock_schemes.go
  pkg/curl/schemes.go
  pkg/curl/schemes_test.go
Labels: Waiting for Reviewer

#2077 Do not print every ping of the watchdog
  pkg/watchdogd/watchdogd.go
Labels: automerge

#2070 Cover all packages, not just package under test
  .circleci/config.yml
Labels: automerge

#2041 Update circleci docker image
  .circleci/config.yml
  integration/testcmd/common/common.go
  integration/testcmd/gotest/uinit/gotest.go
  pkg/mount/mount_integration_test.go
  pkg/qemu/devices.go
  pkg/vfile/testdata/key0
  pkg/vfile/testdata/key1
  pkg/vfile/vfile_test.go
Labels: Waiting for Author, automerge

#1834 uroot_test: add riscv to the build tests
  uroot_test.go
Labels: automerge

#2076 vmtest: use same Go version to compile initramfs and Go tests
  pkg/vmtest/gotest.go
Labels: automerge
