Repository u-root/u-root, pull requests merged in 2021-11, with the labels that each got.

#2156 uio: introduce ArchiveReader wrapper reading archive
  go.mod
  go.sum
  pkg/uio/archivereader.go
  pkg/uio/archivereader_test.go
  vendor/github.com/pierrec/lz4/v4/.gitignore
  vendor/github.com/pierrec/lz4/v4/LICENSE
  vendor/github.com/pierrec/lz4/v4/README.md
  vendor/github.com/pierrec/lz4/v4/go.mod
  vendor/github.com/pierrec/lz4/v4/go.sum
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/blocks.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_amd64.s
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_arm.s
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_arm64.s
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_asm.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4block/decode_other.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4errors/errors.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4stream/block.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4stream/frame.go
  vendor/github.com/pierrec/lz4/v4/internal/lz4stream/frame_gen.go
  vendor/github.com/pierrec/lz4/v4/internal/xxh32/xxh32zero.go
  vendor/github.com/pierrec/lz4/v4/internal/xxh32/xxh32zero_arm.go
  vendor/github.com/pierrec/lz4/v4/internal/xxh32/xxh32zero_arm.s
  vendor/github.com/pierrec/lz4/v4/internal/xxh32/xxh32zero_other.go
  vendor/github.com/pierrec/lz4/v4/lz4.go
  vendor/github.com/pierrec/lz4/v4/options.go
  vendor/github.com/pierrec/lz4/v4/options_gen.go
  vendor/github.com/pierrec/lz4/v4/reader.go
  vendor/github.com/pierrec/lz4/v4/state.go
  vendor/github.com/pierrec/lz4/v4/state_gen.go
  vendor/github.com/pierrec/lz4/v4/writer.go
  vendor/modules.txt
Labels: automerge

#2058 cmds/exp/netbootxyz: Show download progress
  cmds/exp/netbootxyz/network.go
Labels: automerge

#1965 Add more info when init is missing
  pkg/uroot/uroot.go
  pkg/uroot/uroot_test.go
Labels: automerge, Awaiting reviewer

#2186 vendor/netlink: update github.com/vishvananda/netlink to latest master
  cmds/core/ip/ops_linux.go
  go.mod
  go.sum
  vendor/github.com/vishvananda/netlink/.travis.yml
  vendor/github.com/vishvananda/netlink/README.md
  vendor/github.com/vishvananda/netlink/addr.go
  vendor/github.com/vishvananda/netlink/addr_linux.go
  vendor/github.com/vishvananda/netlink/bpf_linux.go
  vendor/github.com/vishvananda/netlink/class_linux.go
  vendor/github.com/vishvananda/netlink/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/devlink_linux.go
  vendor/github.com/vishvananda/netlink/filter.go
  vendor/github.com/vishvananda/netlink/filter_linux.go
  vendor/github.com/vishvananda/netlink/handle_linux.go
  vendor/github.com/vishvananda/netlink/handle_unspecified.go
  vendor/github.com/vishvananda/netlink/inet_diag.go
  vendor/github.com/vishvananda/netlink/ipset_linux.go
  vendor/github.com/vishvananda/netlink/link.go
  vendor/github.com/vishvananda/netlink/link_linux.go
  vendor/github.com/vishvananda/netlink/neigh.go
  vendor/github.com/vishvananda/netlink/neigh_linux.go
  vendor/github.com/vishvananda/netlink/netlink_unspecified.go
  vendor/github.com/vishvananda/netlink/netns_linux.go
  vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go
  vendor/github.com/vishvananda/netlink/nl/devlink_linux.go
  vendor/github.com/vishvananda/netlink/nl/ipset_linux.go
  vendor/github.com/vishvananda/netlink/nl/link_linux.go
  vendor/github.com/vishvananda/netlink/nl/lwt_linux.go
  vendor/github.com/vishvananda/netlink/nl/nl_linux.go
  vendor/github.com/vishvananda/netlink/nl/parse_attr_linux.go
  vendor/github.com/vishvananda/netlink/nl/rdma_link_linux.go
  vendor/github.com/vishvananda/netlink/nl/seg6_linux.go
  vendor/github.com/vishvananda/netlink/nl/syscall.go
  vendor/github.com/vishvananda/netlink/nl/tc_linux.go
  vendor/github.com/vishvananda/netlink/qdisc.go
  vendor/github.com/vishvananda/netlink/qdisc_linux.go
  vendor/github.com/vishvananda/netlink/rdma_link_linux.go
  vendor/github.com/vishvananda/netlink/route.go
  vendor/github.com/vishvananda/netlink/route_linux.go
  vendor/github.com/vishvananda/netlink/route_unspecified.go
  vendor/github.com/vishvananda/netlink/rule.go
  vendor/github.com/vishvananda/netlink/rule_linux.go
  vendor/github.com/vishvananda/netlink/socket_linux.go
  vendor/github.com/vishvananda/netlink/tcp.go
  vendor/github.com/vishvananda/netlink/tcp_linux.go
  vendor/github.com/vishvananda/netlink/xfrm_policy.go
  vendor/github.com/vishvananda/netlink/xfrm_policy_linux.go
  vendor/github.com/vishvananda/netlink/xfrm_state.go
  vendor/github.com/vishvananda/netlink/xfrm_state_linux.go
  vendor/modules.txt
Labels: automerge

#2183 cover/cmds/core/cat
  cmds/core/cat/cat.go
  cmds/core/cat/cat_test.go
Labels: automerge, Awaiting reviewer, coverage
