Repository u-root/u-root, pull requests merged in 2022-05, with the labels that each got.

#2389 shutdown: fix it, it was broken by test creation
  cmds/core/shutdown/shutdown_linux.go
  cmds/core/shutdown/shutdown_linux_test.go
Labels: Bug, Awaiting reviewer

#2393 cpio: fix to allow a same file as source for multiple extra files
  pkg/cpio/fs_unix.go
Labels: Awaiting author

#2395 pkg/mount: do not MkdirAll the mountpoint by default
  integration/testcmd/common/common.go
  pkg/mount/mount_linux.go
  pkg/mount/mount_linux_test.go
Labels: Code Health, automerge, Awaiting reviewer, breaks API

#2398 Fix RUNLOCAL to work
  integration/.gitignore
  integration/RUNLOCAL
Labels: Bug, Awaiting reviewer

#2399 pkg/libinit: migrate from syscall to golang.org/x/sys
  pkg/libinit/proc_linux.go
  pkg/libinit/root_linux.go
Labels: Awaiting reviewer

#2406 Skip unit test if /dev/tty not present
  pkg/pty/pty_test.go
  pkg/termios/termios_test.go
Labels: Awaiting author
