Repository u-root/u-root, pull requests merged in 2022-06, with the labels that each got.

#2228 System call filter package and sample command
  cmds/exp/syscallfilter/main_linux.go
  integration/gotests/gotest_test.go
  pkg/syscallfilter/doc.go
  pkg/syscallfilter/syscallfilter_linux.go
  pkg/syscallfilter/syscallfilter_linux_test.go
Labels: Awaiting reviewer

#2417 Change print to commit directly before the merge of #2256
  u-root.go
Labels: automerge, Awaiting author

#2383 efivars: aesthetics fixes
  cmds/exp/efivarfs/efivarfs.go
  pkg/efivarfs/vars.go
  pkg/efivarfs/vars_test.go
Labels: Awaiting author

#2386 boot: support device tree for syslinux boot
  pkg/boot/linux.go
  pkg/boot/linux_test.go
  pkg/boot/syslinux/syslinux.go
  pkg/boot/syslinux/syslinux_test.go
Labels: Awaiting author

#2421 Remove cirrus ci
  .cirrus.yml
Labels: automerge, Awaiting reviewer

#2425 Bump up integration tests timeout.
  .circleci/config.yml
Labels: automerge

#2426 Update rsdpgetter order
  pkg/acpi/rsdp_linux.go
Labels: automerge

#2423 Refactor align pkg.
  pkg/align/align.go
  pkg/align/align_test.go
  pkg/boot/align/align.go
  pkg/boot/align/align_test.go
  pkg/boot/kexec/memory_linux.go
  pkg/boot/kexec/object.go
  pkg/boot/multiboot/module.go
  pkg/boot/purgatory/purg_load.go
  pkg/dt/fdt.go
  pkg/strace/print.go
  pkg/strace/socket.go
  pkg/uio/buffer.go
Labels: automerge

#2424 Add device tree helpers for booting arm64
  pkg/dt/fdt_linux.go
  pkg/dt/fdt_test.go
  pkg/dt/node.go
  pkg/dt/node_test.go
Labels: Awaiting reviewer

#2430 Migrate integration test qemu version to 7.0.0
  .circleci/config.yml
  .circleci/images/builduploadall.sh
  .circleci/images/test-image-amd64/Dockerfile
  .circleci/images/test-image-arm/Dockerfile
  .circleci/images/test-image-arm64/Dockerfile
Labels: Awaiting reviewer

#2428 Add parser for arm64 Image header.
  pkg/boot/image/image.go
  pkg/boot/image/image_test.go
  pkg/boot/image/testdata/Image
Labels: automerge, Awaiting author, kexec

#2434 pkg/vpd, tools/vpdbootmanager: add 'dump' to read and print VPD value…
  pkg/vpd/flashromvpd.go
  tools/vpdbootmanager/add.go
  tools/vpdbootmanager/main.go
Labels: automerge, Awaiting author

#2435 zircon: implement basic Zircon boot image parser
  cmds/exp/zbi/zbi.go
  pkg/boot/zbi/testdata/chain-load-test.zbi
  pkg/boot/zbi/testdata/x86-boot-shim-tests.zbi
  pkg/boot/zbi/testdata/zbi-chain-load-hello-world-test.zbi
  pkg/boot/zbi/zbi.go
  pkg/boot/zbi/zbi_test.go
Labels: automerge, Awaiting author

#2436 Update test-integration-amd64 to large resource class in config.yml
  .circleci/config.yml
Labels: automerge, Awaiting reviewer

#2438 Aesthetics fixups
  pkg/boot/kexec/doc.go
  pkg/boot/kexec/kexec_fileload_other_linux.go
  pkg/boot/kexec/memory_linux.go
  pkg/boot/linux/load_linux_amd64.go
  pkg/boot/linux/load_other_linux.go
  pkg/boot/purgatory/asm.go
  pkg/boot/zbi/zbi.go
  pkg/dt/fdt_test.go
  pkg/dt/node.go
  pkg/syscallfilter/doc.go
  pkg/syscallfilter/syscallfilter_linux.go
  pkg/uefivars/boot/boot.go
  pkg/uroot/builder/builder.go
Labels: automerge, Awaiting reviewer
