Repository u-root/u-root, pull requests merged in 2022-04, with the labels that each got.

#2373 cmds/core/backoff:
  cmds/core/backoff/main_test.go
  cmds/core/backoff/run.go
Labels: coverage

#2375 unix build tag does not exist
  cmds/core/init/fns_other.go
  cmds/core/init/fns_unix.go
Labels: automerge

#2138 Add efivarfs support
  cmds/exp/efivarfs/efivarfs.go
  cmds/exp/efivarfs/efivarfs_test.go
  go.mod
  go.sum
  pkg/efivarfs/doc.go
  pkg/efivarfs/varfs.go
  pkg/efivarfs/varfs_test.go
  pkg/efivarfs/vars.go
  pkg/efivarfs/vars_test.go
  pkg/libinit/root_linux.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/null.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2378 gosh: fix ambiguous info message
  cmds/exp/gosh/gosh.go
Labels: automerge, Awaiting author

#2385 Add extlinux support to syslinux pkg
  pkg/boot/syslinux/syslinux.go
Labels: Awaiting author
