Repository u-root/u-root, pull requests merged in 2022-03, with the labels that each got.

#2340 testing: use `T.TempDir` to create temporary test directory
  cmds/core/cat/cat_test.go
  cmds/core/hexdump/hexdump_test.go
  cmds/core/ls/ls_linux_test.go
  cmds/core/ls/ls_test.go
  cmds/core/mkdir/mkdir_test.go
  cmds/core/mknod/mknod_linux_test.go
  cmds/core/mv/mv_test.go
  cmds/core/sync/sync_test.go
  pkg/cp/cp_test.go
  pkg/memio/ports_linux_test.go
  tools/vpdbootmanager/add_test.go
  tools/vpdbootmanager/main_test.go
Labels: Code Health, automerge, Awaiting author

#2318 Cover/cmds/exp/bzimage: Add tests.
  cmds/exp/bzimage/bzimage.go
  cmds/exp/bzimage/bzimage_test.go
Labels: Awaiting author, coverage

#2334 Cover/cmds/exp/pox: Add tests.
  cmds/exp/pox/pox.go
  cmds/exp/pox/pox_test.go
  cmds/exp/pox/pox_vm_test.go
Labels: Awaiting author, coverage

#2343 Remove cmds/exp/validate and it's dependency
  cmds/exp/validate/validate.go
  cmds/exp/validate/validate_test.go
  vendor/golang.org/x/crypto/md4/md4.go
  vendor/golang.org/x/crypto/md4/md4block.go
  vendor/golang.org/x/crypto/ripemd160/ripemd160.go
  vendor/golang.org/x/crypto/ripemd160/ripemd160block.go
  vendor/golang.org/x/crypto/sha3/doc.go
  vendor/golang.org/x/crypto/sha3/hashes.go
  vendor/golang.org/x/crypto/sha3/hashes_generic.go
  vendor/golang.org/x/crypto/sha3/keccakf.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.go
  vendor/golang.org/x/crypto/sha3/keccakf_amd64.s
  vendor/golang.org/x/crypto/sha3/register.go
  vendor/golang.org/x/crypto/sha3/sha3.go
  vendor/golang.org/x/crypto/sha3/sha3_s390x.go
  vendor/golang.org/x/crypto/sha3/sha3_s390x.s
  vendor/golang.org/x/crypto/sha3/shake.go
  vendor/golang.org/x/crypto/sha3/shake_generic.go
  vendor/golang.org/x/crypto/sha3/xor.go
  vendor/golang.org/x/crypto/sha3/xor_generic.go
  vendor/golang.org/x/crypto/sha3/xor_unaligned.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2351 termios: make struct Termios contain unix.Termios, not *unix.Termios
  pkg/termios/termios_darwin.go
  pkg/termios/termios_linux.go
  pkg/termios/termios_test.go
  pkg/termios/var_unix.go
Labels: automerge, Awaiting author

#2348 templates: add 'embedded' for embedded system, e.g. ARM gadgets
  templates.go
Labels: automerge, Awaiting author

#2346 cover: cmds/core/yes:
  cmds/core/yes/yes.go
  cmds/core/yes/yes_test.go
Labels: Awaiting author, coverage

#2307 Cover/cmds/core/md5sum: Add tests.
  cmds/core/md5sum/md5sum.go
  cmds/core/md5sum/md5sum_test.go
Labels: automerge, coverage

#2355 Remove cmds/exp/rush
  cmds/exp/rush/attr.go
  cmds/exp/rush/attr_linux.go
  cmds/exp/rush/cd.go
  cmds/exp/rush/exit.go
  cmds/exp/rush/info.go
  cmds/exp/rush/parse.go
  cmds/exp/rush/rush.go
  cmds/exp/rush/rush_test.go
  cmds/exp/rush/time.go
  cmds/exp/rush/tty.go
  cmds/exp/rush/tty_linux.go
Labels: Code Health, Awaiting author, coverage

#2331 Cover/cmds/core/truncate: Add tests.
  cmds/core/truncate/truncate.go
  cmds/core/truncate/truncate_test.go
Labels: Awaiting author, coverage

#2357 Remove: cmds/exp/cksum:
  cmds/exp/cksum/cksum.go
  cmds/exp/cksum/cksum_test.go
Labels: Code Health, Awaiting reviewer, coverage

#2319 Cover/cmds/core/chroot: Add tests.
  cmds/core/chroot/chroot.go
  cmds/core/chroot/chroot_test.go
Labels: Awaiting author, coverage

#2359 Cover/cmds/exp/cbmem: Add tests.
  cmds/exp/cbmem/cbmem_linux_test.go
  cmds/exp/cbmem/main_linux.go
  cmds/exp/cbmem/timestamps.go
  cmds/exp/cbmem/timestamps_test.go
Labels: Awaiting author, coverage

#2360 Cover/cmds/exp/ed: Add tests. Part 1
  cmds/exp/ed/address_test.go
  cmds/exp/ed/filebuffer_test.go
Labels: Awaiting author, coverage

#2361 Cover/cmds/exp/ed: Add tests. Part 2
  cmds/exp/ed/commands.go
  cmds/exp/ed/ed.go
  cmds/exp/ed/ed_test.go
  integration/gotests/gotest_test.go
Labels: Awaiting author, coverage

#2320 Cover/cmds/core/shasum: Add tests.
  cmds/core/shasum/shasum.go
  cmds/core/shasum/shasum_test.go
Labels: Awaiting author, coverage

#2362 Cover/cmds/core/shutdown: Add tests.
  cmds/core/shutdown/shutdown_linux.go
  cmds/core/shutdown/shutdown_test.go
Labels: Awaiting reviewer, coverage

#2363 Fix flaky tests of cmds/core/date
  cmds/core/date/date.go
  cmds/core/date/date_test.go
  cmds/core/date/date_unix.go
Labels: Code Health, automerge, Awaiting author

#2368 Fix rm
  cmds/core/rm/rm.go
  cmds/core/rm/rm_test.go
Labels: Code Health, Awaiting reviewer, coverage

#2369 Fix truncate to not drop garbage in integration tests
  cmds/core/truncate/truncate.go
Labels: Awaiting reviewer, coverage

#2370 cmds/core/comm: fix it to handle error
  cmds/core/comm/comm.go
  cmds/core/comm/comm_test.go
Labels: Code Health, automerge, Awaiting reviewer, coverage
