Repository u-root/u-root, pull requests merged in 2022-10, with the labels that each got.

#2503 df: add support for passing file arguments
  cmds/core/df/dev.go
  cmds/core/df/dev_uint32.go
  cmds/core/df/df.go
  cmds/core/df/df_test.go
Labels: automerge, Awaiting author

#2512 pkg/efivarfs: correctly fix tmpdir removal
  pkg/efivarfs/fs_test.go
Labels: automerge, Awaiting reviewer

#2508 cmds/core/ls: fix multiple problems around permissions
  cmds/core/ls/ls.go
  cmds/core/ls/ls_plan9.go
  cmds/core/ls/ls_test.go
  cmds/core/ls/ls_unix.go
  pkg/cmdline/cmdline_test.go
Labels: Awaiting reviewer

#2515 cmds/core/which: fix default usage
  cmds/core/which/which.go
  cmds/core/which/which_test.go
Labels: automerge, Awaiting author

#2518 pkg/dhclient: Allow custom client v6 port
  pkg/dhclient/dhclient.go
Labels: automerge

#2519 pkg/syscallfilter: remove test obsoleted by go 1.19
  pkg/syscallfilter/syscallfilter_linux_test.go
Labels: Awaiting reviewer

#2539 fix unchecked errors in cmds/exp/netbootxyz & pkg/boot
  cmds/exp/netbootxyz/netbootxyz.go
  pkg/boot/fit/vfit.go
  pkg/boot/uefi/uefi.go
Labels: Awaiting reviewer

#2541 cmds/core/ip: parse gateway IP instead of CIDR
  cmds/core/ip/ip_linux.go
Labels: automerge, Awaiting author

#2543 oss-fuzz integration prep: add dictionaries & .options to improve fuz…
  cmds/boot/localboot/testdata/fuzz/fuzz_parse_grub_cfg.options
  docs/fuzzing/fuzzing.md
  pkg/boot/grub/testdata/fuzz/fuzz_parse_grub_config.options
  pkg/boot/grub/testdata/fuzz/grub.dict
  pkg/boot/syslinux/testdata/fuzz/fuzz_parse_syslinux_config.options
  pkg/boot/syslinux/testdata/fuzz/parse_syslinux_cfg.dict
  pkg/cpio/testdata/fuzz/cpio.dict
  pkg/cpio/testdata/fuzz/fuzz_read_write_newc.options
Labels: Awaiting reviewer
