Repository u-root/u-root, pull requests merged in 2022-12, with the labels that each got.

#2573 libinit: Export types and functions
  pkg/libinit/root_linux.go
Labels: Awaiting author

#2574 cmds/core/date: set test error output to bytes.Buffer
  cmds/core/date/date_test.go
Labels: Awaiting reviewer

#2568 ci: add CIFuzz Github action
  .github/workflows/cifuzz.yml
Labels: automerge, Awaiting author

#2580 /pkg/mount/block: Expose ComposePartName function
  pkg/mount/block/blockdev_linux.go
  pkg/mount/block/blockdev_test.go
Labels: Awaiting reviewer
