Repository u-root/u-root, pull requests merged in 2022-07, with the labels that each got.

#2441 u-root.go: set a reasonable and checked default for -uroot-source
  u-root.go
Labels: Awaiting author, Awaiting reviewer

#2453 Add helper function to create initrd
  cmds/core/kexec/kexec_linux.go
  pkg/boot/initrd.go
  pkg/boot/initrd_test.go
Labels: automerge, Awaiting author

#2457 Update go-tpm to deal with dependabot alerts
  go.mod
  go.sum
  vendor/github.com/google/go-tpm/tpm/commands.go
  vendor/github.com/google/go-tpm/tpm/constants.go
  vendor/github.com/google/go-tpm/tpm/open_other.go
  vendor/github.com/google/go-tpm/tpm/structures.go
  vendor/github.com/google/go-tpm/tpm/testing.md
  vendor/github.com/google/go-tpm/tpm/tpm.go
  vendor/github.com/google/go-tpm/tpm2/constants.go
  vendor/github.com/google/go-tpm/tpm2/error.go
  vendor/github.com/google/go-tpm/tpm2/open_other.go
  vendor/github.com/google/go-tpm/tpm2/structures.go
  vendor/github.com/google/go-tpm/tpm2/tpm2.go
  vendor/github.com/google/go-tpm/tpmutil/run.go
  vendor/github.com/google/go-tpm/tpmutil/run_other.go
  vendor/github.com/google/go-tpm/tpmutil/structures.go
  vendor/github.com/google/go-tpm/tpmutil/tbs/tbs_windows.go
  vendor/modules.txt
Labels: Code Health, automerge, Awaiting reviewer

#2454 Create v0.9.0 release notes
  RELEASES
Labels: automerge
