Repository u-root/u-root, pull requests merged in 2022-01, with the labels that each got.

#2251 fix cmds/core/date tests.
  cmds/core/date/date_test.go
Labels: automerge

#2255 Add basic MAINTAINERS file
  .github/workflows/auto-assign.yml
  MAINTAINERS
Labels: Awaiting reviewer

#2184 Coverage pkg/rtc
  pkg/rtc/pkg_test.go
  pkg/rtc/rtc.go
  pkg/rtc/rtc_linux.go
  pkg/rtc/rtc_linux_test.go
  pkg/rtc/rtc_notlinux.go
Labels: Awaiting reviewer, coverage

#2259 Remove pkg/kexecbin.
  pkg/kexecbin/kexecbin.go
  pkg/kexecbin/pkg_test.go
Labels: Code Health, automerge

#2213 tarutil: Add ChangeDirectory feature
  integration/testcmd/common/common.go
  pkg/tarutil/tar.go
  pkg/tarutil/tar_test.go
Labels: Awaiting reviewer

#2245 remove testify dependency
  go.mod
  pkg/boot/jsonboot/bootconfig_test.go
  pkg/boot/systembooter/bootentry_test.go
  pkg/crypto/ed25519_test.go
  pkg/mount/block/blockdev_test.go
  pkg/namespace/builder_test.go
  pkg/namespace/namespace_test.go
  pkg/namespace/parser_test.go
  pkg/ntpdate/ntpdate_test.go
  pkg/progress/progress_test.go
  pkg/uzip/uzip_test.go
  pkg/vpd/vpd_test.go
  tools/vpdbootmanager/add_test.go
  tools/vpdbootmanager/get_test.go
  tools/vpdbootmanager/main_test.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: automerge

#2244 pkg/memio - Rework&Cover
  pkg/memio/archport_linux.go
  pkg/memio/io_test.go
  pkg/memio/memio_ports.go
  pkg/memio/mmap_linux.go
  pkg/memio/mmap_test.go
  pkg/memio/path_linux.go
  pkg/memio/ports.go
  pkg/memio/ports_linux.go
  pkg/memio/ports_linux_test.go
  pkg/memio/ports_plan9.go
  pkg/memio/ports_test.go
  pkg/memio/seek.go
  pkg/memio/uintn_test.go
Labels: Code Health, Awaiting reviewer, coverage

#2277 Add /etc/passwd file to integration tests.
  integration/gotests/gotest_test.go
Labels: automerge, Awaiting author

#2265 Cover/cmds/core/hexdump
  cmds/core/hexdump/hexdump.go
  cmds/core/hexdump/hexdump_test.go
Labels: automerge, coverage

#2278 Add ByName and ByNumber functions, to get system call numbers and names
  pkg/strace/epsocket.go
  pkg/strace/print.go
  pkg/strace/syscall_linux.go
  pkg/strace/syscalls.go
  pkg/strace/syscalls_test.go
  pkg/strace/tracer.go
Labels: automerge

#2226 echo.go & echo_test.go: Refactored echo pkg and added tests.
  cmds/core/echo/echo.go
  cmds/core/echo/echo_test.go
Labels: automerge, coverage

#2268 Cover/cmds/core/mkdir
  cmds/core/mkdir/mkdir.go
  cmds/core/mkdir/mkdir_test.go
Labels: Awaiting author, coverage

#2280 pogosh: Delete
  cmds/exp/pogosh/pogosh.go
  pkg/pogosh/arithmetic.go
  pkg/pogosh/arithmetic_test.go
  pkg/pogosh/ast.go
  pkg/pogosh/builtins.go
  pkg/pogosh/exec.go
  pkg/pogosh/lexer.go
  pkg/pogosh/lexer_test.go
  pkg/pogosh/parser.go
  pkg/pogosh/shell.go
  pkg/pogosh/shell_test.go
  pkg/pogosh/state.go
Labels: automerge

#2274 CI/Integrate IPMI capabilities to kernel and qemu for integration tests
  .circleci/config.yml
  .circleci/images/test-image-amd64/config_linux5.10_x86_64.txt
Labels: Awaiting reviewer

#2288 README: clarify module support
  README.md
Labels: automerge

#2269 Cover/cmds/core/mv
  cmds/core/mv/mv.go
  cmds/core/mv/mv_test.go
Labels: Awaiting reviewer, coverage

#2267 Cover/cmds/core/dmesg
  cmds/core/dmesg/dmesg.go
  cmds/core/dmesg/dmesg_test.go
Labels: automerge, Awaiting author, coverage

#2293 exp/disk_unlock: print hints if password mismatch
  cmds/exp/disk_unlock/disk_unlock.go
Labels: Awaiting author

#2266 Cover/cmds/core/mknod
  cmds/core/mknod/mknod.go
  cmds/core/mknod/mknod_linux.go
  cmds/core/mknod/mknod_linux_test.go
  cmds/core/mknod/mknod_test.go
Labels: automerge, Awaiting author, coverage

#2270 Cover/cmds/core/ls
  cmds/core/ls/ls.go
  cmds/core/ls/ls_linux_test.go
  cmds/core/ls/ls_test.go
Labels: automerge, Awaiting author, coverage

#2271 Cover/cmds/core/ping
  cmds/core/ping/ping.go
  cmds/core/ping/ping_test.go
Labels: automerge, Awaiting author, coverage

#2295 Cover/pkg/pci
  pkg/pci/bits_test.go
  pkg/pci/devices.go
  pkg/pci/devices_test.go
  pkg/pci/lookup_test.go
  pkg/pci/pci_test.go
Labels: automerge, Awaiting author, coverage

#2297 Cover/cmds/core/kill
  cmds/core/kill/kill.go
  cmds/core/kill/kill_test.go
Labels: automerge, Awaiting author, coverage

#2298 Cover/cmds/core/rm
  cmds/core/rm/rm.go
  cmds/core/rm/rm_test.go
Labels: automerge, Awaiting author, coverage

#2299 Cover/cmds/core/ps
  cmds/core/ps/ps.go
  cmds/core/ps/ps_linux.go
  cmds/core/ps/ps_test.go
Labels: automerge, Awaiting reviewer, coverage
