Repository u-root/u-root, pull requests merged in 2022-11, with the labels that each got.

#2546 Fix broken link
  README.md
Labels: Awaiting author

#2501 libinit: Implement ErrNoModulesFound
  pkg/libinit/root_linux.go
Labels: automerge, Awaiting author

#2530 CI: replace golint with revive and run ineffassign in subdirectories
  .github/workflows/go.yml
  cmds/exp/cbmem/main_linux.go
  cmds/exp/ssh/main.go
  pkg/boot/uefi/uefi.go
  pkg/cpio/archive_test.go
  pkg/ipmi/ocp/bootorder.go
  pkg/smbios/type0_bios_information_test.go
  pkg/smbios/type1_system_information_test.go
  pkg/smbios/type2_baseboard_information_test.go
  pkg/smbios/type43_tpm_device_test.go
  pkg/smbios/type7_cache_information_test.go
  pkg/smbios/type9_system_slots_test.go
  pkg/watchdogd/watchdogd.go
Labels: automerge, Awaiting author

#2556 Fix error checking fbnetboot/main.go
  cmds/boot/fbnetboot/main.go
Labels: automerge, Awaiting author

#2557 [fbnetboot] Fix error in retry logic.
  cmds/boot/fbnetboot/main.go
Labels: automerge, Awaiting author

#2560 pkg/dt: Move kernel-independent parts of parsing to fdt.go
  pkg/dt/fdt.go
  pkg/dt/fdt_linux.go
Labels: Awaiting reviewer

#2555 cmds/exp/gosh: fuzzing of gosh cmd
  cmds/exp/gosh/gosh_test.go
  cmds/exp/gosh/testdata/fuzz/corpora/1.seed
  cmds/exp/gosh/testdata/fuzz/corpora/2.seed
  cmds/exp/gosh/testdata/fuzz/corpora/3.seed
  cmds/exp/gosh/testdata/fuzz/corpora/4.seed
  cmds/exp/gosh/testdata/fuzz/corpora/5.seed
  cmds/exp/gosh/testdata/fuzz/corpora/6.seed
  cmds/exp/gosh/testdata/fuzz/corpora/7.seed
  cmds/exp/gosh/testdata/fuzz/fuzz_gosh_run.options
  cmds/exp/gosh/testdata/fuzz/gosh.dict
Labels: Awaiting author

#2561 pkg/dt: create idiomatic New(), minimize Linux special-ness
  pkg/dt/fdt.go
  pkg/dt/fdt_linux.go
  pkg/dt/fdt_test.go
Labels: Awaiting reviewer

#2542 cmds/core/tee add test coverage
  cmds/core/tee/tee.go
  cmds/core/tee/tee_test.go
Labels: automerge, Awaiting author

#2569 bugfix/gosh:
  cmds/exp/gosh/gosh.go
  cmds/exp/gosh/gosh_test.go
  gosh
Labels: Awaiting reviewer

#2572 oss-fuzz: replace t.TempDir()
  cmds/boot/localboot/grub_test.go
  cmds/exp/gosh/gosh_test.go
  pkg/boot/grub/config_test.go
  pkg/boot/syslinux/syslinux_test.go
Labels: automerge, Awaiting author

#2537 Add tool for unlocking TCG Opal-secured NVMe drives
  cmds/exp/disk_unlock/disk_unlock.go
  cmds/exp/nvme_unlock/nvme_unlock.go
  pkg/hsskey/hsskey.go
  pkg/hsskey/hsskey_test.go
Labels: Awaiting author
