Repository u-root/u-root, pull requests merged in 2022-09, with the labels that each got.

#2372 cmds/core/timeout: add a timeout command
  cmds/core/timeout/main.go
  cmds/core/timeout/main_test.go
Labels: Feature Request, Awaiting reviewer

#2479 ldd: Ignore symlinks that lead to the same file
  pkg/ldd/ldd_unix.go
  pkg/ldd/ldd_unix_test.go
Labels: automerge, Awaiting author

#2490 pkg/cmdline: make it more idiomatic and testable
  cmds/boot/boot/boot.go
  pkg/cmdline/cmdline.go
  pkg/cmdline/cmdline_linux.go
  pkg/cmdline/cmdline_other.go
  pkg/cmdline/cmdline_test.go
  pkg/cmdline/filters.go
  pkg/cmdline/filters_test.go
Labels: automerge, Awaiting reviewer

#2496 add codeql badge
  README.md
Labels: automerge, Awaiting reviewer

#2491 wget: no cache is needed.
  cmds/core/wget/wget.go
Labels: Awaiting author

#2499 based64: fix a bug and make it more testable
  cmds/core/base64/base64.go
  cmds/core/base64/base64_test.go
Labels: automerge, Awaiting reviewer

#2482 Support more ways to load kernel modules early
  cmds/core/init/init_linux.go
  pkg/libinit/root_linux.go
  pkg/libinit/root_linux_test.go
Labels: Awaiting reviewer

#2504 cmds/core/id: modify to make it more testable, followed up
  cmds/core/id/id_test.go
Labels: automerge

#2505 cmds/core/kill: Create an unused port for testing kill
  cmds/core/kill/kill_test.go
Labels: automerge, Awaiting author
