Repository u-root/u-root, pull requests merged in 2022-08, with the labels that each got.

#2459 Create SECURITY.md
  SECURITY.md
Labels: automerge, Awaiting author

#2445 watchdogd: log disarm op more accurately.
  pkg/watchdogd/watchdogd.go
Labels: automerge

#2442 u-root.go: test for relative paths with os.Stat()
  u-root.go
Labels: automerge, Awaiting author

#2468 README.md: Add network-less instructions
  README.md
Labels: automerge, Awaiting author

#2460 boot: remove duplicate device tree field
  cmds/core/kexec/kexec_linux.go
  pkg/boot/linux.go
  pkg/boot/linux/opts.go
  pkg/boot/linux_test.go
  pkg/boot/syslinux/syslinux.go
  pkg/boot/syslinux/syslinux_test.go
  pkg/dt/fdt_linux.go
  pkg/dt/fdt_test.go
Labels: automerge

#2469 Add TeeOutput function to logutil
  pkg/logutil/logutil.go
  pkg/logutil/logutil_test.go
Labels: automerge

#2470 (test cleanup) Add subtest to bzimage_test.go
  pkg/boot/bzimage/bzimage_test.go
Labels: automerge

#2472 Small fix for linux_test.go
  pkg/boot/linux_test.go
Labels: automerge

#2471 cmds/exp/bzimage: change to use standard Go flag package
  cmds/exp/bzimage/bzimage.go
Labels: automerge, Awaiting reviewer

#2486 Change zstd decompressor to use Go package instead of forking a command.
  pkg/boot/bzimage/bzimage.go
  pkg/boot/bzimage/bzimage_decompress.go
  pkg/boot/bzimage/bzimage_test.go
Labels: automerge

#2485 cmds/core/wget: Fix unit test unused port
  cmds/core/wget/wget_test.go
Labels: Awaiting author
