Repository u-root/u-root, pull requests merged in 2022-02, with the labels that each got.

#2291 CONTRIBUTION.md: Add details about vmtest side effects.
  CONTRIBUTING.md
Labels: automerge, Awaiting author

#2296 Cover/cmds/core/pci
  cmds/core/pci/pci.go
  cmds/core/pci/pci_test.go
  cmds/core/pci/testfiles/testfile1.json
  cmds/core/pci/testfiles/testfile2.json
Labels: automerge, Awaiting author, coverage

#2301 cmds/core/mknod: Remove SkipIfNotRoot
  cmds/core/mknod/mknod_linux_test.go
Labels: Awaiting reviewer, coverage

#2302 Cover/cmds/core/wc: Add tests.
  cmds/core/wc/testfiles/file1
  cmds/core/wc/testfiles/file2
  cmds/core/wc/wc.go
  cmds/core/wc/wc_test.go
Labels: Awaiting reviewer, coverage

#2303 Cover/cmds/core/uniq: Add tests.
  cmds/core/uniq/testfiles/file1
  cmds/core/uniq/testfiles/file2
  cmds/core/uniq/uniq.go
  cmds/core/uniq/uniq_test.go
Labels: automerge, coverage

#2304 Cover/cmds/core/comm: Add tests.
  cmds/core/comm/comm.go
  cmds/core/comm/comm_test.go
Labels: Awaiting author, coverage

#2315 Re-enable pkg/bb test.
  pkg/bb/bb_test.go
Labels: Awaiting author

#2306 Cover/cmds/core/strings: Add tests.
  cmds/core/strings/strings.go
  cmds/core/strings/strings_test.go
Labels: automerge, coverage

#2308 Cover/cmds/core/sort: Add tests.
  cmds/core/sort/sort.go
  cmds/core/sort/sort_test.go
Labels: automerge, coverage

#2305 Cover/cmds/core/cmp: Add tests.
  cmds/core/cmp/cmp.go
  cmds/core/cmp/cmp_test.go
Labels: automerge, Awaiting author, coverage

#2323 kexec: Object common-ize access to Progs and Entry
  pkg/boot/kexec/object.go
  pkg/boot/kexec/object_test.go
Labels: automerge, kexec

#2321 A few tweaks / improvements to bzimage.
  pkg/boot/bzimage/bzimage.go
Labels: Awaiting reviewer, kexec

#2332 Cover/cmds/core/chmod: Add tests.
  cmds/core/chmod/chmod.go
  cmds/core/chmod/chmod_test.go
Labels: Awaiting reviewer
