Repository u-root/u-root, pull requests merged in 2023-07, with the labels that each got.

#2710 pkg/ldd: show Stderr output of interpreter in case of ExitError
  pkg/ldd/ldd_unix.go
Labels: automerge, Awaiting author

#2714 cmds/core/grep: remove unused struct and rearrange fields
  cmds/core/grep/grep.go
Labels: Awaiting author

#2717 boot/localboot/grub.go: Fix typo
  cmds/boot/localboot/grub.go
Labels: automerge, Awaiting author

#2719 cmds/core/find: add missing file types
  cmds/core/find/find.go
Labels: automerge, Awaiting author

#2718 kcmdline: improve command-line parsing & tests
  pkg/cmdline/cmdline.go
  pkg/cmdline/cmdline_test.go
Labels: Awaiting author

#2709 Fix argument name for shasum command
  cmds/core/shasum/shasum.go
Labels: automerge, Awaiting author

#2732 update test images
  .circleci/config.yml
  .circleci/images/builduploadall.sh
  .circleci/images/test-image-arm/Dockerfile
  .circleci/images/test-image-tamago/Dockerfile
Labels: automerge, Awaiting reviewer

#2730 strace: add riscv64 to pkg and cmd
  cmds/core/strace/strace_linux.go
  pkg/strace/arch.go
  pkg/strace/epsocket.go
  pkg/strace/epsocket_test.go
  pkg/strace/print.go
  pkg/strace/socket.go
  pkg/strace/syscall_linux.go
  pkg/strace/syscall_linux_riscv64.go
  pkg/strace/syscalls.go
  pkg/strace/syscalls_test.go
  pkg/strace/tracer.go
  pkg/strace/tracer_test.go
  pkg/strace/types.go
Labels: Awaiting reviewer

#2724 cmds/core/ping: fix counter bug
  cmds/core/ping/ping.go
Labels: automerge, Awaiting author
