Repository u-root/u-root, pull requests merged in 2023-09, with the labels that each got.

#2753 cmds/core/uniq: remove global flags
  cmds/core/uniq/uniq.go
  cmds/core/uniq/uniq_test.go
Labels: Awaiting author

#2756 cmds/core/tail: simplify loops and remove global flags
  cmds/core/tail/tail.go
  cmds/core/tail/tail_test.go
Labels: Awaiting author

#2759 cmds/core/cpio: add tests for list
  cmds/core/cpio/cpio.go
  cmds/core/cpio/cpio_test.go
Labels: Awaiting author

#2752 pkg/mount/magic.go: Add BTRFS magic value
  pkg/mount/magic.go
Labels: automerge, Awaiting author

#2760 cmds/core/mkdir: fix empty mode test if umask is not 022
  cmds/core/mkdir/mkdir_test.go
Labels: Awaiting reviewer

#2746 Fix /etc/ lossage in CreateRootfs
  pkg/libinit/root_linux.go
Labels: automerge, Awaiting author

#2755 pkg/boot/linux.go: Decompress kernel before doing kexec
  pkg/boot/jsonboot/bootconfig.go
  pkg/boot/linux.go
  pkg/boot/linux_test.go
Labels: Awaiting author

#2761 cmds/core/seq: remove global flags, reflect and simplify tests
  cmds/core/seq/seq.go
  cmds/core/seq/seq_test.go
Labels: Awaiting reviewer

#2764 update go-tpm
  go.mod
  go.sum
  vendor/github.com/google/go-tpm/tpm2/pcrs.go
  vendor/github.com/google/go-tpm/tpm2/reflect.go
  vendor/github.com/google/go-tpm/tpm2/structures.go
  vendor/github.com/google/go-tpm/tpm2/tpm2.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2766 cmds/contrib: rename files so it only tries to build on linux
  cmds/contrib/flash/dummy_linux.go
  cmds/contrib/flash/flash_linux.go
  cmds/contrib/spidev/spidev_linux.go
  cmds/contrib/spidev/spidev_linux_test.go
  pkg/flash/flash_linux.go
  pkg/flash/flash_linux_test.go
  pkg/flash/spimock/spimock_linux.go
Labels: Awaiting reviewer

#2767 cmds/core/mv: remove globals flags
  cmds/core/mv/mv.go
  cmds/core/mv/mv_test.go
Labels: Awaiting author

#2770 cmds/core/more: add more tests
  cmds/core/more/more.go
  cmds/core/more/more_test.go
Labels: Awaiting author

#2772 cmds/core/uname: add tests, remove domain flag
  cmds/core/uname/uname.go
  cmds/core/uname/uname_test.go
Labels: Awaiting reviewer
