Repository u-root/u-root, pull requests merged in 2023-04, with the labels that each got.

#2648 pkg/uzip: remove deprecated
  pkg/uzip/uzip.go
  pkg/uzip/uzip_test.go
Labels: Awaiting reviewer

#2652 Add CreateTeeWriter function to logutil
  pkg/logutil/logutil.go
Labels: Awaiting reviewer

#2653 cmds/core/time: add -p flag to time command
  cmds/core/time/time.go
Labels: Awaiting author

#2655 netboot: trim down heap allocations.
  pkg/boot/initrd.go
  pkg/boot/linux.go
  pkg/boot/netboot/ipxe/ipxe.go
  pkg/curl/schemes.go
  pkg/uio/lazy.go
  pkg/uio/lazy_test.go
Labels: automerge, Awaiting reviewer

#2658 cmds/core/grep: fix line number (-n)
  cmds/core/grep/grep.go
  cmds/core/grep/grep_test.go
Labels: Awaiting reviewer

#2663 Strings format
  cmds/core/strings/strings.go
  cmds/core/strings/strings_test.go
Labels: Awaiting author

#2659 Add file limit to cpio file creation
  pkg/cpio/fs_unix.go
  pkg/uio/lazy.go
  pkg/uio/lazy_test.go
Labels: automerge, Awaiting reviewer
