Repository u-root/u-root, pull requests merged in 2023-01, with the labels that each got.

#2585 cmds/core/tr: increase coverage and remove testutil
  cmds/core/tr/tr.go
  cmds/core/tr/tr_test.go
Labels: automerge, Awaiting author

#2597 Add ttyhvc0 to libinit
  pkg/libinit/root_linux.go
Labels: automerge, Awaiting author

#2601 Forthcleanup -- fix up code, tests, etc.
  cmds/exp/forth/forth.go
  pkg/forth/forth.go
  pkg/forth/forth_test.go
Labels: Awaiting reviewer

#2600 cifuzz: do not report non-reproducible crashes
  .github/workflows/cifuzz.yml
  cmds/core/gosh/testdata/fuzz/fuzz_gosh_run.options
Labels: Awaiting author

#2567 cmds/core/cat: handle "-" to comply with POSIX
  cmds/core/cat/cat.go
  cmds/core/cat/cat_test.go
Labels: Awaiting author

#2595 Fix follow mode in tail
  cmds/core/tail/tail.go
Labels: Awaiting author

#2563 [mktemp] Remove hard coded /tmp in mktemp_test.go
  cmds/core/mktemp/mktemp.go
  cmds/core/mktemp/mktemp_test.go
Labels: Awaiting author

#2605 cmds/core/ip: fix arg parsing
  cmds/core/ip/ip_linux.go
Labels: automerge, Awaiting author
