Repository u-root/u-root, pull requests merged in 2023-10, with the labels that each got.

#2773 cmds/core/tee: remove globals
  cmds/core/tee/tee.go
Labels: Awaiting reviewer

#2776 cmds/core/hostname: tests and change build suffix
  cmds/core/hostname/hostname.go
  cmds/core/hostname/hostname_linux.go
  cmds/core/hostname/hostname_test.go
Labels: Awaiting author

#2777 cmds/exp/crc: add tests
  cmds/exp/crc/crc.go
  cmds/exp/crc/crc_test.go
Labels: automerge, Awaiting author

#2779 move contrib/ to fwtools/
  MAINTAINERS
  cmds/fwtools/flash/dummy_linux.go
  cmds/fwtools/flash/flash_linux.go
  cmds/fwtools/flash/spi_linux.go
  cmds/fwtools/spidev/spidev_linux.go
  cmds/fwtools/spidev/spidev_linux_test.go
Labels: Awaiting reviewer

#2771 /pkg/hsskey: Include backup HSS
  pkg/hsskey/hsskey.go
Labels: Awaiting author

#2782 cmds/core/xargs: minimal xargs, just passing args
  cmds/core/xargs/xargs.go
  cmds/core/xargs/xargs_test.go
Labels: Awaiting reviewer

#2790 pci: fix json annotation for BARs
  cmds/core/pci/testfiles/testfile1.json
  pkg/pci/pci.go
Labels: automerge, Awaiting author

#2794 pkg/align: add support for baremetal (tinygo / tamago)
  pkg/align/align.go
  pkg/align/pagesize.go
  pkg/align/pagesize_baremetal.go
Labels: Awaiting reviewer
