Repository u-root/u-root, pull requests merged in 2023-06, with the labels that each got.

#2690 HSS: Support reading HSS from EEPROM
  cmds/exp/disk_unlock/disk_unlock.go
  cmds/exp/nvme_unlock/nvme_unlock.go
  pkg/hsskey/filereader.go
  pkg/hsskey/filereader_test.go
  pkg/hsskey/hsskey.go
Labels: Awaiting reviewer

#2696 Remove unused DCE test
  uroot_test.go
Labels: automerge, Awaiting author

#2697 cmds/core/sort: ignore blanks break ties by length
  cmds/core/sort/sort.go
  cmds/core/sort/sort_test.go
Labels: Awaiting author

#2699 Add stdin, stdout, stderr options to StartShell struct
  pkg/boot/menu/menu.go
  pkg/libinit/proc.go
Labels: Awaiting author

#2704 cmds/core/sort: add numeric flag
  cmds/core/sort/sort.go
  cmds/core/sort/sort_test.go
Labels: Awaiting author

#2703 update to go-tpm 0.9.0
  go.mod
  go.sum
  pkg/securelaunch/tpm/tpm.go
  pkg/tss/capabilities.go
  pkg/tss/nvram.go
  pkg/tss/pcr.go
  pkg/tss/tpm_linux.go
  pkg/tss/tss.go
  vendor/github.com/google/go-tpm/legacy/tpm2/README.md
  vendor/github.com/google/go-tpm/legacy/tpm2/constants.go
  vendor/github.com/google/go-tpm/legacy/tpm2/error.go
  vendor/github.com/google/go-tpm/legacy/tpm2/kdf.go
  vendor/github.com/google/go-tpm/legacy/tpm2/open_other.go
  vendor/github.com/google/go-tpm/legacy/tpm2/open_windows.go
  vendor/github.com/google/go-tpm/legacy/tpm2/structures.go
  vendor/github.com/google/go-tpm/legacy/tpm2/tpm2.go
  vendor/github.com/google/go-tpm/tpm/open_other.go
  vendor/github.com/google/go-tpm/tpmutil/poll_other.go
  vendor/github.com/google/go-tpm/tpmutil/poll_unix.go
  vendor/github.com/google/go-tpm/tpmutil/run.go
  vendor/github.com/google/go-tpm/tpmutil/run_other.go
  vendor/github.com/google/go-tpm/tpmutil/structures.go
  vendor/github.com/google/go-tpm/tpmutil/tbs/tbs_windows.go
  vendor/modules.txt
Labels: Awaiting author
