Repository u-root/u-root, pull requests merged in 2023-11, with the labels that each got.

#2799 cmds/exp/srvfiles: add tests
  cmds/exp/srvfiles/srvfiles_test.go
Labels: Awaiting author

#2762 fbptcat: dump raw contents of FBPT table
  .circleci/images/test-image-amd64/config_linux.txt
  cmds/contrib/fbptcat/fbptcat.go
  pkg/acpi/fpdt/fbpt/fbpt.go
  pkg/acpi/fpdt/fbpt/fbpt_test.go
  pkg/acpi/fpdt/fpdt.go
  pkg/acpi/fpdt/fpdt_test.go
Labels: automerge, Awaiting author

#2788 boot/localboot: make initramfs optional
  cmds/boot/localboot/main.go
Labels: automerge, Awaiting author

#2803 cpio/utils: use path, not filepath, on archives
  pkg/cpio/utils.go
Labels: Awaiting reviewer

#2800 cmds/core/sync: move sync under linux build tag
  cmds/core/sync/sync.go
  cmds/core/sync/sync_linux.go
  cmds/core/sync/sync_test.go
  cmds/core/sync/sync_unix.go
Labels: Awaiting author

#2801 Add a readelf command
  cmds/exp/readelf/readelf.go
  cmds/exp/readelf/readelf_test.go
  cmds/exp/readelf/testdata/a
  cmds/exp/readelf/testdata/a.S
  cmds/exp/readelf/testdata/out
Labels: Awaiting reviewer

#2806 cmds/core/xargs: add max-args flag
  cmds/core/xargs/xargs.go
  cmds/core/xargs/xargs_test.go
Labels: Awaiting reviewer

#2793 Add reading HSS from arbitrary files
  cmds/exp/disk_unlock/disk_unlock.go
  cmds/exp/nvme_unlock/nvme_unlock.go
  pkg/hsskey/filereader.go
  pkg/hsskey/filereader_test.go
  pkg/hsskey/hsskey.go
Labels: Awaiting reviewer

#2807 cmds/core/cat: make files variadic and io tests
  cmds/core/cat/cat.go
  cmds/core/cat/cat_test.go
Labels: automerge, Awaiting author

#2808 cmds/core/xargs: add trace flag
  cmds/core/xargs/xargs.go
  cmds/core/xargs/xargs_test.go
Labels: Awaiting author

#2809 Fix dmesg test so that testtool works in CI
  cmds/core/dmesg/dmesg.go
  cmds/core/dmesg/dmesg_test.go
Labels: automerge, Awaiting author

#2810 if /dev/fuse does not exist, skip fusermount tests
  cmds/core/fusermount/fusermount.go
  cmds/core/fusermount/fusermount_linux_test.go
Labels: Awaiting author

#2811 cmds/core/xargs: add promt flag
  cmds/core/xargs/xargs.go
  cmds/core/xargs/xargs_test.go
Labels: Awaiting author

#2812 cmds/core: rename lsdrivers and timeout
  cmds/core/lsdrivers/lsdrivers_linux.go
  cmds/core/timeout/timeout.go
  cmds/core/timeout/timeout_test.go
Labels: Awaiting author

#2815 tinygobb: update and make it work again
  cmds/exp/rush/rush_tinygo.go
  tools/tinygobb/main.go
Labels: Awaiting reviewer
