Repository u-root/u-root, pull requests merged in 2023-03, with the labels that each got.

#2637 menu: allow passing in loadOptions
  pkg/boot/menu/menu.go
Labels: automerge

#2641 id remove testutils, add more tests
  cmds/core/id/id.go
  cmds/core/id/id_test.go
Labels: Awaiting author

#2642 u-root command: add checkArgs function
  u-root.go
  uroot_test.go
Labels: Awaiting reviewer

#2639 Add allowlist filtering for PCI devices
  pkg/mount/block/blockdev_linux.go
  pkg/mount/block/blockdev_test.go
Labels: Awaiting reviewer

#2644 cmds/core/base64: remove deprecated ioutil
  cmds/core/base64/base64_test.go
Labels: automerge, Awaiting author

#2645 cmds/core/tail: use io.SeekEnd instead of deprecated os.SEEK_END
  cmds/core/tail/tail.go
Labels: Awaiting reviewer
