Repository u-root/u-root, pull requests merged in 2024-06, with the labels that each got.

#2992 cmds/core/kill: some bsd syscalls tables
  cmds/core/kill/kill_test.go
  cmds/core/kill/list_darwin.go
  cmds/core/kill/list_freebsd.go
  cmds/core/kill/list_linux.go
  cmds/core/kill/list_netbsd.go
  cmds/core/kill/list_openbsd.go
  cmds/core/kill/siglist.go
Labels: Awaiting author

#2990 cmds/core/man: add tests
  cmds/core/man/gen/gen_test.go
  cmds/core/man/gen/testdata/cat/cat.go
Labels: Awaiting author

#2999 pkg/strace: tests for binary package
  pkg/strace/internal/binary/binary_test.go
Labels: Awaiting author

#3007 golangcilint print line numbers
  .github/workflows/golangci-lint.yml
Labels: Awaiting reviewer

#3009 uroot/util: add unixflag processing
  cmds/core/ls/ls.go
  cmds/core/ls/ls_plan9.go
  cmds/core/ls/ls_test.go
  pkg/uroot/unixflag/unixflag.go
  pkg/uroot/unixflag/unixflag_test.go
Labels: Awaiting reviewer

#3001 Remove hardcoding of "/etc/resolv.conf" in WriteDNSSettings()
  pkg/dhclient/dhclient.go
  pkg/dhclient/dhcp4.go
  pkg/dhclient/dhcp6.go
Labels: automerge, Awaiting author

#3016 docs: update README for webiste deployments
  README.md
Labels: automerge, Awaiting author

#2973 spidev: process arguments for raw command
  cmds/fwtools/spidev/spidev_linux.go
  cmds/fwtools/spidev/spidev_linux_test.go
Labels: Awaiting reviewer

#3020 cmds/core/ls: Fix flag parsing
  cmds/core/ls/ls.go
Labels: automerge

#3024 pkg/rand: add fallback test for linux
  pkg/rand/random_linux_test.go
Labels: Awaiting author

#3025 cmds/core/strace: fix build for arm64 and tests
  cmds/core/strace/strace_linux.go
  cmds/core/strace/strace_linux_test.go
Labels: Awaiting author

#3030 exp/pox: add the binary in since ldd.List no longer does
  cmds/exp/pox/pox.go
Labels: Awaiting reviewer

#3034 pkg/find: add more options tests
  pkg/find/find_test.go
Labels: Awaiting author
