Repository u-root/u-root, pull requests merged in 2024-12, with the labels that each got.

#3156 cmds/core/tail: fix bug of tail -f
  cmds/core/tail/tail.go
Labels: Awaiting reviewer

#3221 Fix call to traceroute without arguments prints help.
  cmds/exp/traceroute/main.go
Labels: automerge, Awaiting author

#3237 cmds/core/free: use go-humanize for human output
  cmds/core/free/free_linux.go
  cmds/core/free/free_linux_test.go
Labels: Awaiting author

#3240 cmds/core/ps: use slices.Max
  cmds/core/ps/ps_linux.go
Labels: Awaiting author

#3242 pkg/mount: determine fstype using statfs type
  pkg/mount/magic.go
  pkg/mount/mount_linux.go
Labels: Awaiting author

#3249 pkg/namespace: remove built-in redefinitions
  pkg/namespace/builder_test.go
  pkg/namespace/namespace.go
Labels: Awaiting author

#3250 pkg/namespace: remove more built-in redefinitions
  pkg/namespace/namespace.go
  pkg/namespace/namespace_test.go
  pkg/namespace/namespace_unix.go
Labels: Awaiting author

#3252 cmds/core/dmesg: remove unused struct
  cmds/core/dmesg/dmesg_linux.go
Labels: Awaiting author

#3254 cmds/exp/serial: serial communication program
  cmds/exp/serial/serial.go
  cmds/exp/serial/serial_test.go
  go.mod
  go.sum
  vendor/github.com/creack/goselect/.gitignore
  vendor/github.com/creack/goselect/Dockerfile
  vendor/github.com/creack/goselect/LICENSE
  vendor/github.com/creack/goselect/README.md
  vendor/github.com/creack/goselect/fdset.go
  vendor/github.com/creack/goselect/fdset_32.go
  vendor/github.com/creack/goselect/fdset_64.go
  vendor/github.com/creack/goselect/fdset_doc.go
  vendor/github.com/creack/goselect/fdset_freebsd.go
  vendor/github.com/creack/goselect/fdset_unsupported.go
  vendor/github.com/creack/goselect/fdset_windows.go
  vendor/github.com/creack/goselect/select.go
  vendor/github.com/creack/goselect/select_linux.go
  vendor/github.com/creack/goselect/select_other.go
  vendor/github.com/creack/goselect/select_unsupported.go
  vendor/github.com/creack/goselect/select_windows.go
  vendor/github.com/creack/goselect/test_crosscompile.sh
  vendor/github.com/creack/goselect/zselect_windows.go
  vendor/go.bug.st/serial/LICENSE
  vendor/go.bug.st/serial/README.md
  vendor/go.bug.st/serial/doc.go
  vendor/go.bug.st/serial/serial.go
  vendor/go.bug.st/serial/serial_bsd.go
  vendor/go.bug.st/serial/serial_darwin.go
  vendor/go.bug.st/serial/serial_darwin_386.go
  vendor/go.bug.st/serial/serial_darwin_64.go
  vendor/go.bug.st/serial/serial_freebsd.go
  vendor/go.bug.st/serial/serial_linux.go
  vendor/go.bug.st/serial/serial_openbsd.go
  vendor/go.bug.st/serial/serial_resetbuf_linux_bsd.go
  vendor/go.bug.st/serial/serial_specialbaudrate_linux.go
  vendor/go.bug.st/serial/serial_specialbaudrate_linux_ppc64le.go
  vendor/go.bug.st/serial/serial_unix.go
  vendor/go.bug.st/serial/serial_windows.go
  vendor/go.bug.st/serial/syscall_windows.go
  vendor/go.bug.st/serial/unixutils/pipe.go
  vendor/go.bug.st/serial/unixutils/select.go
  vendor/go.bug.st/serial/zsyscall_windows.go
  vendor/modules.txt
Labels: Awaiting author

#3255 cmds/exp/page: restore terminal back if case of signal
  cmds/exp/page/page.go
Labels: Awaiting reviewer
