Repository u-root/u-root, pull requests merged in 2024-09, with the labels that each got.

#3090 cmds/core/du: add -L flag
  cmds/core/du/du.go
  cmds/core/du/du_test.go
Labels: Awaiting author

#3087 tinygo: fix pkg/kmodule/compression{,_tinygo}.go build tags
  pkg/kmodule/compression.go
  pkg/kmodule/compression_tinygo.go
Labels: Awaiting author

#3092 cmds/core/du: rewrite to unixflag
  cmds/core/du/du.go
  cmds/core/du/du_test.go
Labels: Awaiting author

#3098 FIX: cmds/exp/tftp: read buffer adaption and last read correction
  pkg/tftp/tftp.go
Labels: Awaiting reviewer

#3100 cmds/core/cat: remove redundant error handling
  cmds/core/cat/cat.go
Labels: Awaiting author

#3101 cmds/core/readlink: pass stdout instead stdin
  cmds/core/readlink/readlink.go
Labels: automerge, Awaiting author

#3110 cmds/exp/tcpdump: add check if transport layer is present
  cmds/exp/tcpdump/main.go
Labels: Awaiting reviewer

#3112 staticcheck: fix SA1006 Printf with dynamic
  cmds/core/rsdp/rsdp.go
  cmds/core/shutdown/shutdown_linux.go
  cmds/exp/pflask/pflask.go
  cmds/exp/pflask/termios.go
  cmds/exp/zbi/zbi.go
Labels: Awaiting author

#3116 cmds/core/basename: return with non zero status on error
  cmds/core/basename/basename.go
  cmds/core/basename/basename_test.go
Labels: Awaiting author

#3121 pkg/ipmi: remove buf.Bytes()[2] <= 0xFF check
  pkg/ipmi/ipmi.go
Labels: Awaiting author
