Repository u-root/u-root, pull requests merged in 2024-04, with the labels that each got.

#2957 cmds/core/touch: cleanup error handling with errors.Join
  cmds/core/touch/access_linux_test.go
  cmds/core/touch/touch.go
  cmds/core/touch/touch_test.go
Labels: Awaiting reviewer

#2955 pkg/namespace: basename first argument
  pkg/namespace/parser.go
  pkg/namespace/parser_test.go
Labels: automerge

#2962 cmds/core/kill: use errors.Join instead of []error
  cmds/core/kill/kill_test.go
  cmds/core/kill/signaler_unix.go
Labels: Awaiting author

#2961 cmds/core/wget: handle "-" as stdout
  cmds/core/wget/wget.go
  cmds/core/wget/wget_test.go
Labels: Awaiting reviewer

#2964 cmds/core/chroot: simplify error handling
  cmds/core/chroot/chroot.go
Labels: Awaiting author

#2967 cmds/core/unshare: align godoc with recent default shell
  cmds/core/unshare/unshare_linux.go
Labels: Awaiting author

#2966 cmds/core/sshd: fix race condition
  cmds/core/sshd/sshd.go
  cmds/core/sshd/sshd_test.go
Labels: Awaiting author

#2972 Add a CITATION.cff
  CITATION.cff
Labels: Awaiting reviewer

#2965 /cmds/core/uptime: increase test coverage
  cmds/core/uptime/uptime.go
  cmds/core/uptime/uptime_test.go
Labels: Awaiting author

#2968 pkg/termios: remove err check that never true
  pkg/termios/sgtty.go
Labels: Awaiting author

#2975 cmds/core/uniq: use testdata folder for tests
  cmds/core/uniq/testdata/file1.txt
  cmds/core/uniq/testdata/file2.txt
  cmds/core/uniq/uniq_test.go
Labels: Awaiting author

#2969 cmds/core/unshare: add tests
  cmds/core/unshare/unshare_linux.go
  cmds/core/unshare/unshare_linux_test.go
Labels: Awaiting author
