Repository u-root/u-root, pull requests merged in 2024-02, with the labels that each got.

#2881 memmap: rename /sys/firmware/memmap parser
  cmds/exp/dumpmemmap/main_linux.go
  pkg/boot/kexec/memory_map_linux.go
  pkg/boot/kexec/memory_map_linux_test.go
  pkg/boot/linux/load_linux_amd64.go
  pkg/boot/multiboot/multiboot.go
  pkg/boot/uefi/uefi.go
  pkg/boot/uefi/uefi_test.go
Labels: Awaiting reviewer

#2896 Replace pkg/uio with uio/uio
  cmds/core/cp/cp_test.go
  cmds/core/kexec/kexec_linux.go
  cmds/core/wget/wget.go
  cmds/exp/madeye/madeye.go
  go.mod
  go.sum
  pkg/boot/boottest/same_image.go
  pkg/boot/esxi/esxi.go
  pkg/boot/esxi/esxi_test.go
  pkg/boot/grub/grub.go
  pkg/boot/ibft/ibft.go
  pkg/boot/initrd.go
  pkg/boot/initrd_test.go
  pkg/boot/linux.go
  pkg/boot/linux/load_linux.go
  pkg/boot/linux/load_linux_amd64.go
  pkg/boot/linux_test.go
  pkg/boot/multiboot/description.go
  pkg/boot/multiboot/module.go
  pkg/boot/multiboot/multiboot.go
  pkg/boot/multiboot/mutiboot_info.go
  pkg/boot/netboot/ipxe/ipxe.go
  pkg/boot/netboot/ipxe/ipxe_test.go
  pkg/boot/syslinux/syslinux.go
  pkg/boot/util/reader.go
  pkg/cpio/fs_plan9.go
  pkg/cpio/fs_unix.go
  pkg/cpio/fs_windows.go
  pkg/cpio/newc.go
  pkg/cpio/newc_test.go
  pkg/cpio/utils.go
  pkg/curl/schemes.go
  pkg/curl/schemes_test.go
  pkg/dt/fdt.go
  pkg/gzip/file.go
  pkg/securelaunch/launcher/launcher.go
  pkg/strace/tracer_test.go
  pkg/uio/alignreader.go
  pkg/uio/alignwriter.go
  pkg/uio/archivereader.go
  pkg/uio/archivereader_test.go
  pkg/uio/buffer.go
  pkg/uio/cached.go
  pkg/uio/cached_test.go
  pkg/uio/lazy.go
  pkg/uio/lazy_test.go
  pkg/uio/linewriter.go
  pkg/uio/null.go
  pkg/uio/progress.go
  pkg/uio/progress_test.go
  pkg/uio/reader.go
  pkg/uio/reader_test.go
  pkg/uio/uio.go
  pkg/uio/uiotest/pkg_test.go
  pkg/uroot/initramfs/files_test.go
  pkg/uroot/initramfs/test/ramfs.go
  uroot_test.go
  vendor/github.com/u-root/uio/uio/lazy.go
  vendor/github.com/u-root/uio/uio/uiotest/uiotest.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2903 kexec,memory: some utilities
  pkg/boot/kexec/memory_linux.go
  pkg/boot/kexec/memory_linux_test.go
  pkg/boot/kexec/memory_map_linux.go
Labels: Awaiting reviewer

#2904 Make gosh default shell
  README.md
  cmds/core/sshd/const_unix.go
  integration/gotests/gotest_test.go
  templates.go
  u-root.go
Labels: Awaiting reviewer

#2902 Modify boot.OSImages
  cmds/boot/boot/boot.go
  pkg/boot/boot.go
  pkg/boot/boot_test.go
Labels: Awaiting reviewer

#2913 Swap ubinary.NativeEndian for binary.NativeEndian
  pkg/acpi/fpdt/fpdt.go
  pkg/boot/multiboot/header.go
  pkg/boot/multiboot/info.go
  pkg/boot/multiboot/internal/trampoline/trampoline_linux_amd64.go
  pkg/boot/multiboot/module.go
  pkg/boot/multiboot/multiboot.go
  pkg/boot/multiboot/mutiheader.go
  pkg/memio/memio_ports.go
  pkg/strace/epsocket.go
  pkg/strace/socket.go
  pkg/strace/tracer.go
  pkg/ubinary/big_endian.go
  pkg/ubinary/doc.go
  pkg/ubinary/little_endian.go
  pkg/ubinary/pkg_test.go
Labels: Awaiting reviewer

#2915 fix ST1005 incorrectly formatted error string
  .golangci.yml
  cmds/exp/lsfabric/lsfabric.go
  pkg/boot/linux/load_linux_image.go
Labels: Awaiting reviewer

#2916 pkg/boot/bzimage: type should have the same receiver name
  .golangci.yml
  pkg/boot/bzimage/kver.go
Labels: Awaiting reviewer

#2919 pkg/spidev: uintptr can't be negative
  .golangci.yml
  pkg/spidev/spidev_linux_test.go
Labels: Awaiting reviewer

#2921 fix Printf with dynamic first argument and no further arguments
  .golangci.yml
  pkg/pci/devices.go
  pkg/progress/progress.go
Labels: Awaiting reviewer

#2922 cmds/exp/ectool: add explicit type to constants
  .golangci.yml
  cmds/exp/ectool/commands.go
Labels: Awaiting reviewer

#2925 Remove kr/pty dependency
  cmds/exp/newsshd/newsshd.go
  go.mod
  go.sum
  vendor/github.com/kr/pty/.gitignore
  vendor/github.com/kr/pty/LICENSE
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/shim.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2931 fix linter version
  .github/workflows/golangci-lint.yml
Labels: Awaiting reviewer

#2936 pkg/dt: fix revive superfluous-else linter
  pkg/dt/fdt.go
Labels: automerge, Awaiting author

#2935 Remove unused files
  examples/fixmynetboot/main.go
  files/etc/profile.d/uroot.sh
  tricksandtips.md
Labels: Awaiting reviewer

#2897 gosh with tab completion and history with small dependencies
  cmds/core/gosh/completer.go
  cmds/core/gosh/completer_common.go
  cmds/core/gosh/completer_liner.go
  cmds/core/gosh/completer_nobuild.go
  cmds/core/gosh/completer_test.go
  go.mod
  go.sum
  vendor/github.com/peterh/liner/COPYING
  vendor/github.com/peterh/liner/README.md
  vendor/github.com/peterh/liner/bsdinput.go
  vendor/github.com/peterh/liner/common.go
  vendor/github.com/peterh/liner/fallbackinput.go
  vendor/github.com/peterh/liner/input.go
  vendor/github.com/peterh/liner/input_darwin.go
  vendor/github.com/peterh/liner/input_linux.go
  vendor/github.com/peterh/liner/input_solaris.go
  vendor/github.com/peterh/liner/input_windows.go
  vendor/github.com/peterh/liner/line.go
  vendor/github.com/peterh/liner/output.go
  vendor/github.com/peterh/liner/output_solaris.go
  vendor/github.com/peterh/liner/output_unix.go
  vendor/github.com/peterh/liner/output_windows.go
  vendor/github.com/peterh/liner/unixmode.go
  vendor/github.com/peterh/liner/unixmode_solaris.go
  vendor/github.com/peterh/liner/width.go
  vendor/modules.txt
Labels: Awaiting reviewer

#2937 cmds/exp/ectool: fix revive superfluous-else linter
  cmds/exp/ectool/ectool.go
Labels: Awaiting author

#2932 pkg/dt,pkg/boot/bls: remove unused variables
  .golangci.yml
  pkg/boot/bls/bls.go
  pkg/dt/fdt_test.go
Labels: Awaiting author
