Repository u-root/u-root, pull requests merged in 2024-11, with the labels that each got.

#3158 Seccomp-bpf tracing
  pkg/strace/tracer.go
Labels: Awaiting reviewer

#3161 cmds/core/xargs: add null to use null byte as delimiter
  cmds/core/xargs/xargs.go
  cmds/core/xargs/xargs_test.go
Labels: Awaiting author

#3163 Add Seccomp Support to Trace Function
  pkg/strace/tracer.go
Labels: automerge, Awaiting reviewer

#3171 Fix securelaunch vm tests
  pkg/securelaunch/vm_test.go
Labels: Awaiting reviewer

#3182 cmds/core/ip: update help text for unsupported options
  cmds/core/ip/ip_linux.go
  cmds/core/ip/link_linux.go
  cmds/core/ip/tunnel_linux.go
  cmds/core/ip/xfrm_linux.go
  cmds/core/ip/xfrm_policy_linux.go
Labels: Awaiting reviewer

#3181 cmds/exp/tc: Add help to toplevel tc command.
  cmds/exp/tc/main.go
  cmds/exp/tc/tc_test.go
Labels: Awaiting author

#3184 cmds/exp/tc: add help message for wrong, no args
  cmds/exp/tc/tc.go
  cmds/exp/tc/tc_test.go
Labels: Awaiting reviewer

#3186 Fix brctl/show functionality
  pkg/brctl/brctl.go
Labels: Awaiting reviewer

#3197 cmds/core/ip: fix parsing of ip addr flush
  cmds/core/ip/address_linux.go
Labels: Awaiting author

#3199 cmds/core/ip: add newline to end of tcpmetrics subcommand help text
  cmds/core/ip/tcp_metrics_linux.go
Labels: Awaiting author

#3187 simplify dd and let it use go runtime and kernel intelligence
  cmds/core/dd/dd.go
  cmds/core/dd/dd_test.go
Labels: Awaiting reviewer

#3204 cmds/core/ip: fix getState returning incorrect state
  cmds/core/ip/neigh_linux.go
  cmds/core/ip/neigh_linux_test.go
Labels: Awaiting reviewer

#3196 cmds/core/ip: link set: support any combination of attributes
  cmds/core/ip/link_linux.go
Labels: Awaiting reviewer
