Repository u-root/u-root, pull requests merged in 2024-01, with the labels that each got.

#2835 pkg/dhcplient: remove redurant fmt.Sprintf
  pkg/dhclient/dhcp6.go
Labels: Awaiting author

#2837 cmds/core/chmod: fix issue with multiple files
  cmds/core/chmod/chmod.go
  cmds/core/chmod/chmod_test.go
Labels: Awaiting reviewer

#2846 fix the mtd test if /dev/mtd0 can not be opened
  pkg/mount/mtd/linux_test.go
Labels: Awaiting reviewer

#2848 Spidevchip
  pkg/flash/chips/chips.go
  pkg/flash/chips/chips_test.go
Labels: automerge, Awaiting reviewer

#2851 pkg/acpi: lift loop condition and remove Sprintf
  pkg/acpi/raw.go
Labels: Awaiting reviewer

#2853 fwtools/spidev: use the ID function from pkg spidev
  cmds/fwtools/spidev/spidev_linux.go
  cmds/fwtools/spidev/spidev_linux_test.go
Labels: Awaiting reviewer

#2855 pkg/impi/ocp: remove comparison with boolean constants
  pkg/ipmi/ocp/ocp_linux.go
Labels: Awaiting reviewer

#2858 pkg/gpio: wrap errors and remove second trim
  pkg/gpio/gpio_linux.go
Labels: Awaiting reviewer

#2839 Ping using x/net/icmp
  cmds/core/ping/ping.go
  cmds/core/ping/ping_linux.go
  cmds/core/ping/ping_other.go
  cmds/core/ping/ping_test.go
  vendor/golang.org/x/net/icmp/dstunreach.go
  vendor/golang.org/x/net/icmp/echo.go
  vendor/golang.org/x/net/icmp/endpoint.go
  vendor/golang.org/x/net/icmp/extension.go
  vendor/golang.org/x/net/icmp/helper_posix.go
  vendor/golang.org/x/net/icmp/interface.go
  vendor/golang.org/x/net/icmp/ipv4.go
  vendor/golang.org/x/net/icmp/ipv6.go
  vendor/golang.org/x/net/icmp/listen_posix.go
  vendor/golang.org/x/net/icmp/listen_stub.go
  vendor/golang.org/x/net/icmp/message.go
  vendor/golang.org/x/net/icmp/messagebody.go
  vendor/golang.org/x/net/icmp/mpls.go
  vendor/golang.org/x/net/icmp/multipart.go
  vendor/golang.org/x/net/icmp/packettoobig.go
  vendor/golang.org/x/net/icmp/paramprob.go
  vendor/golang.org/x/net/icmp/sys_freebsd.go
  vendor/golang.org/x/net/icmp/timeexceeded.go
  vendor/modules.txt
Labels: automerge, Awaiting author

#2863 pkg/dhclient: wrap errors
  pkg/dhclient/dhclient.go
  pkg/dhclient/dhcp4.go
  pkg/dhclient/dhcp6.go
  pkg/dhclient/iface.go
  pkg/dhclient/iscsiuri.go
Labels: Awaiting reviewer

#2871 cmds/exp/syscallfilter: build with more architectures
  cmds/exp/syscallfilter/main_linux.go
  pkg/syscallfilter/syscallfilter_linux.go
  pkg/syscallfilter/syscallfilter_linux_test.go
Labels: Awaiting reviewer

#2876 pkg/strace: fix linux/arm64 test
  pkg/strace/syscalls_test.go
Labels: Awaiting reviewer

#2861 cmds/core/hohup: nohup command
  cmds/core/nohup/nohup.go
  cmds/core/nohup/nohup_test.go
Labels: Awaiting reviewer
