Repository u-root/u-root, pull requests merged in 2024-10, with the labels that each got.

#3094 cmds/core/du: fix for relative links
  cmds/core/du/du.go
  cmds/core/du/du_test.go
  cmds/core/du/testdata/rel-symlinks/f1.txt
  cmds/core/du/testdata/rel-symlinks/f2.txt
  cmds/core/du/testdata/rel-symlinks/links/s1.txt
  cmds/core/du/testdata/rel-symlinks/links/s2.txt
Labels: Awaiting author

#3129 golangci: increase timeout
  .github/workflows/golangci-lint.yml
Labels: Awaiting reviewer

#3130 pkg/mount: add freebsd support for Mount, using nmount
  pkg/mount/mount_freebsd.go
Labels: Awaiting reviewer

#3132 add mount_unix.go
  cmds/core/mount/mount_unix.go
Labels: Awaiting reviewer

#3125 cmds/core/head: add stdin support
  cmds/core/head/head.go
  cmds/core/head/head_test.go
Labels: Awaiting author

#3137 cmds/core/ip: use group parameter in link set command
  cmds/core/ip/link_linux.go
Labels: Awaiting reviewer

#3134 correct the kexec documentation concerning -x/--extra
  cmds/core/kexec/kexec_linux.go
Labels: automerge, Awaiting author

#3135 kexec: fix --append switch
  cmds/core/kexec/kexec_linux.go
  cmds/core/kexec/kexec_test.go
Labels: Awaiting reviewer

#3139 cmds/core/which: use test helper
  cmds/core/which/which_test.go
Labels: Awaiting reviewer

#3142 cmds/core/blkid: use io.Writer for output
  cmds/core/blkid/blkid_linux.go
  cmds/core/blkid/blkid_test.go
Labels: Awaiting author

#3141 Fix kmodule uncompress code
  pkg/kmodule/compression.go
  pkg/kmodule/compression_tinygo.go
  pkg/kmodule/gzipit.go
  pkg/kmodule/gzipit_tinygo.go
  pkg/kmodule/kmodule_linux_test.go
Labels: Awaiting reviewer

#3144 cmds/core/ip: wrap errors
  cmds/core/ip/address_linux.go
  cmds/core/ip/ip_linux.go
  cmds/core/ip/link_linux.go
  cmds/core/ip/monitor_linux.go
  cmds/core/ip/ops_linux.go
  cmds/core/ip/route_linux.go
  cmds/core/ip/tunnel_linux.go
  cmds/core/ip/util_linux.go
Labels: Awaiting reviewer

#3145 cmds/core/tty: fix /dev/fd symbolic link
  cmds/core/tty/tty.go
Labels: Awaiting reviewer

#3146 cmds/core/netcat: wrap errors
  cmds/core/netcat/connect.go
  cmds/core/netcat/listen.go
  cmds/core/netcat/netcat.go
Labels: Awaiting reviewer

#3149 cmds/exp: wrap errors
  cmds/exp/bzimage/bzimage.go
  cmds/exp/cbmem/gen/gen.go
  cmds/exp/cbmem/io.go
  cmds/exp/cbmem/main_linux.go
  cmds/exp/cbmem/timestamps.go
  cmds/exp/console/console_linux.go
  cmds/exp/dmidecode/data_linux.go
  cmds/exp/dmidecode/dmidecode.go
  cmds/exp/ed/address.go
  cmds/exp/ed/commands.go
  cmds/exp/ed/ed.go
  cmds/exp/ed/filebuffer.go
  cmds/exp/fbnetboot/main.go
  cmds/exp/freq/freq.go
  cmds/exp/localboot/main.go
  cmds/exp/nvme_unlock/nvme_unlock.go
  cmds/exp/pox/pox.go
  cmds/exp/rush/parse.go
  cmds/exp/rush/runone_unix.go
  cmds/exp/smbios_transfer/smbios_transfer.go
  cmds/exp/ssh/main.go
  cmds/exp/tcpdump/main.go
  cmds/exp/tcz/tcz.go
Labels: Awaiting reviewer

#3150 Big.rat
  pkg/forth/forth.go
  pkg/forth/forth_test.go
Labels: Awaiting reviewer
