Repository u-root/u-root, pull requests merged in 2025-01, with the labels that each got.

#3257 cmds/exp/serial: change exit program as in picocom
  cmds/exp/serial/serial.go
Labels: automerge, Awaiting reviewer

#3263 pkg/netstat: fix parsing of /proc/net/unix
  pkg/netstat/sockets.go
Labels: automerge, Awaiting reviewer

#3261 Add Plan 9 instructions to the README
  README.md
Labels: Awaiting reviewer

#3265 Add shell tag to plan 9 instructions
  README.md
Labels: automerge

#3274 cmds/core/tail: add support for multiple files
  cmds/core/tail/tail.go
  cmds/core/tail/tail_test.go
Labels: Awaiting reviewer

#3279 cmds/exp/ansi: simplify ansi and improve tests
  cmds/exp/ansi/ansi.go
  cmds/exp/ansi/ansi_test.go
Labels: Awaiting reviewer

#3281 netstat integer overflow
  cmds/core/netstat/netstat_linux.go
  pkg/netstat/format.go
  pkg/netstat/interfaces.go
Labels: Awaiting reviewer

#3288 Fix netcat test
  cmds/core/netcat/listen_test.go
Labels: Awaiting reviewer
