Repository u-root/u-root, pull requests merged in 2025-04, with the labels that each got.

#3339 pkg/hsskey: simplify return
  pkg/hsskey/filereader.go
Labels: automerge, Awaiting author

#3342 configs/README.md: add more explanatory text
  configs/README.md
Labels: Awaiting author, Awaiting reviewer

#3345 cmds/core/gosh: remove unnecessary call to Bytes()
  cmds/core/gosh/gosh_test.go
Labels: Awaiting reviewer

#3350 pkg/watchdogd: remove cleanup loop
  pkg/watchdogd/watchdogd.go
Labels: Awaiting author

#3356 cmds/core/echo: use ReplaceAll
  cmds/core/echo/echo.go
Labels: Awaiting reviewer

#3358 golangci: migrate to v2
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: Awaiting author

#3360 cmds/core/ip: add missing newline to print
  cmds/core/ip/route_linux.go
Labels: Awaiting reviewer
